version: "3.4"

services:
  chacket:
    build:
      context: .
      target: local
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file:
      - .env
    networks:
      - default
    command: ["uvicorn", "chacket.chat.main:app"]
    restart: on-failure:5
    volumes:
      - .:/app